# Generated by Django 4.2.3 on 2024-02-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name_plural": "Businesses"},
        ),
    ]
