# Generated by Django 4.2.3 on 2024-02-10 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_alter_business_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Term",
        ),
        migrations.AddField(
            model_name="business",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
