# Generated by Django 4.2.3 on 2024-02-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_rename_title_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="business.quotation",
            ),
        ),
    ]
