# Generated by Django 4.2.3 on 2024-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_alter_lineitem_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="title",
            field=models.CharField(default="Test", max_length=128),
            preserve_default=False,
        ),
    ]
