# Generated by Django 4.2.3 on 2024-02-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_quotation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.business",
            ),
            preserve_default=False,
        ),
    ]
