# Generated by Django 4.2.3 on 2024-02-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_business_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-last_modified"]},
        ),
        migrations.AlterModelOptions(
            name="quotation",
            options={"ordering": ["-last_modified"]},
        ),
    ]
