# Generated by Django 4.2.3 on 2024-02-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0010_alter_product_options_alter_quotation_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="business",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="customer",
        ),
        migrations.DeleteModel(
            name="LineItem",
        ),
        migrations.DeleteModel(
            name="Quotation",
        ),
    ]
