# Generated by Django 4.2.3 on 2024-02-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_no", models.CharField(max_length=128)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("from_contact", models.CharField(max_length=128)),
                ("from_email", models.EmailField(max_length=128)),
                ("from_name", models.CharField(max_length=128)),
                ("to_contact", models.CharField(max_length=128)),
                ("to_email", models.EmailField(max_length=254)),
                ("to_name", models.CharField(max_length=128)),
                ("notes", models.CharField(max_length=128)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_modified"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=128)),
                ("rate", models.PositiveIntegerField(default=1)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="quotations.quotation",
                    ),
                ),
            ],
        ),
    ]
