# Generated by Django 4.2.3 on 2024-02-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
